# Configuration
board_name: DICT_4X4_50
square_len: 0.0862

input_size: [4112,2176]
bs_train: 32
bs_train_rn: 128
bs_val: 64
bs_val_rn: 256
num_workers: 10
train_labels: '/home/iit.local/ademarco/blender-files/combined_file.json'
val_labels: '/home/iit.local/ademarco/blender-files/combined_file.json'
val_images: '/home/iit.local/ademarco/blender-files/'
train_images: '/home/iit.local/ademarco/blender-files/'
