# Configuration
board_name: DICT_4X4_50
square_len: 0.082

input_size: [4112,2176]
bs_train: 32
bs_train_rn: 64
bs_val: 64
bs_val_rn: 128
num_workers: 1
train_labels: '/home/alessia/Desktop/training_dataset.json'
val_labels: '/home/alessia/Desktop/training_dataset.json'
val_images: '/home/alessia/Desktop/training_dataset/'
train_images: '/home/alessia/Desktop/training_dataset/'